name: PDBCleanV2
channels:
  - bioconda
  - conda-forge
dependencies:
  - appnope=0.1.3=pyhd8ed1ab_0
  - argon2-cffi=21.3.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=21.2.0=py310h1961e1f_2
  - asttokens=2.0.5=pyhd8ed1ab_0
  - attrs=21.4.0=pyhd8ed1ab_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - beautifulsoup4=4.11.1=pyha770c72_0
  - biopython=1.83
  - bleach=5.0.1=pyhd8ed1ab_0
  - brotli=1.0.9=h5eb16cf_7
  - brotli-bin=1.0.9=h5eb16cf_7
  - bzip2=1.0.8=h0d85af4_4
  - ca-certificates=2023.5.7=h8857fd0_0
  - certifi=2023.5.7=pyhd8ed1ab_0
  - cffi=1.15.1=py310h96bbf6e_0
  - cvxopt=1.3.0=py310hed5b562_1
  - cycler=0.11.0=pyhd8ed1ab_0
  - cython=0.29.30=py310hd4537e4_0
  - debugpy=1.6.0=py310h9d931ec_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - dsdp=5.8=h6e329d1_1203
  - entrypoints=0.4=pyhd8ed1ab_0
  - executing=0.8.3=pyhd8ed1ab_0
  - fftw=3.3.10=nompi_hf082fe4_102
  - flit-core=3.7.1=pyhd8ed1ab_0
  - fonttools=4.34.4=py310h6c45266_0
  - freetype=2.10.4=h4cff582_1
  - gettext=0.19.8.1=hd1a6beb_1008
  - giflib=5.2.1=hbcb3906_2
  - glib=2.72.1=h2292cb8_0
  - glib-tools=2.72.1=h2292cb8_0
  - glpk=4.65=h0f52abe_1004
  - gmp=6.2.1=h2e338ed_0
  - gsl=2.7=h93259b0_0
  - gst-plugins-base=1.20.3=hda0ba4b_0
  - gstreamer=1.20.3=hdc08c3f_0
  - icu=70.1=h96cf925_0
  - importlib-metadata=4.11.4=py310h2ec42d9_0
  - importlib_resources=5.8.0=pyhd8ed1ab_0
  - ipykernel=6.15.1=pyh736e0ef_0
  - ipython=8.4.0=py310h2ec42d9_0
  - ipython_genutils=0.2.0=py_1
  - ipywidgets=7.7.1=pyhd8ed1ab_0
  - jedi=0.18.1=py310h2ec42d9_1
  - jinja2=3.1.2=pyhd8ed1ab_1
  - jpeg=9e=hac89ed1_2
  - jsonschema=4.7.2=pyhd8ed1ab_0
  - jupyter=1.0.0=py310h2ec42d9_7
  - jupyter_client=7.3.4=pyhd8ed1ab_0
  - jupyter_console=6.4.4=pyhd8ed1ab_0
  - jupyter_core=4.10.0=py310h2ec42d9_0
  - jupyterlab_pygments=0.2.2=pyhd8ed1ab_0
  - jupyterlab_widgets=1.1.1=pyhd8ed1ab_0
  - kiwisolver=1.4.3=py310habb735a_0
  - krb5=1.19.3=hb49756b_0
  - lcms2=2.12=h577c468_0
  - lerc=3.0=he49afe7_0
  - libblas=3.9.0=15_osx64_openblas
  - libbrotlicommon=1.0.9=h5eb16cf_7
  - libbrotlidec=1.0.9=h5eb16cf_7
  - libbrotlienc=1.0.9=h5eb16cf_7
  - libcblas=3.9.0=15_osx64_openblas
  - libclang=14.0.6=default_h55ffa42_0
  - libclang13=14.0.6=default_hb5731bd_0
  - libcxx=14.0.6=hce7ea42_0
  - libdeflate=1.12=hac89ed1_0
  - libedit=3.1.20191231=h0678c8f_2
  - libffi=3.4.2=h0d85af4_5
  - libgfortran=5.0.0=9_3_0_h6c81a4c_23
  - libgfortran5=9.3.0=h6c81a4c_23
  - libglib=2.72.1=hfbcb929_0
  - libiconv=1.16=haf1e3a3_0
  - liblapack=3.9.0=15_osx64_openblas
  - libllvm14=14.0.6=h41df66c_0
  - libogg=1.3.4=h35c211d_1
  - libopenblas=0.3.20=openmp_hb3cd9ec_0
  - libopus=1.3.1=hc929b4f_1
  - libpng=1.6.37=h5a3d3bf_3
  - libpq=14.4=hf6bb32a_0
  - libsodium=1.0.18=hbcb3906_1
  - libtiff=4.4.0=h9847915_1
  - libvorbis=1.3.7=h046ec9c_0
  - libwebp=1.2.2=h28dabe5_0
  - libwebp-base=1.2.2=h0d85af4_1
  - libxcb=1.13=h0d85af4_1004
  - libzlib=1.2.12=hfe4f2af_2
  - llvm-openmp=14.0.4=ha654fa7_0
  - lz4-c=1.9.3=he49afe7_1
  - markupsafe=2.1.1=py310h1961e1f_1
  - matplotlib=3.5.2=py310h2ec42d9_0
  - matplotlib-base=3.5.2=py310h4510841_0
  - matplotlib-inline=0.1.3=pyhd8ed1ab_0
  - metis=5.1.0=h2e338ed_1006
  - mistune=0.8.4=py310he24745e_1005
  - mpfr=4.1.0=h0f52abe_1
  - munkres=1.1.4=pyh9f0ad1d_0
  - muscle=5.1=hb339e23_1
  - mysql-common=8.0.29=h924029e_1
  - mysql-libs=8.0.29=h3cab752_1
  - nbclient=0.6.6=pyhd8ed1ab_0
  - nbconvert=6.5.0=pyhd8ed1ab_0
  - nbconvert-core=6.5.0=pyhd8ed1ab_0
  - nbconvert-pandoc=6.5.0=pyhd8ed1ab_0
  - nbformat=5.4.0=pyhd8ed1ab_0
  - ncurses=6.3=h96cf925_1
  - nest-asyncio=1.5.5=pyhd8ed1ab_0
  - notebook=6.4.12=pyha770c72_0
  - nspr=4.32=hcd9eead_1
  - nss=3.78=ha8197d3_0
  - numpy=1.23.1=py310ha3f357c_0
  - openjpeg=2.4.0=h6e7aa92_1
  - openssl=1.1.1u=h8a1eda9_0
  - packaging=21.3=pyhd8ed1ab_0
  - pandas=2.0.0=py310hecf8f37_0
  - pandoc=2.18=h694c41f_0
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parso=0.8.3=pyhd8ed1ab_0
  - patsy=0.5.3=pyhd8ed1ab_0
  - pcre=8.45=he49afe7_0
  - pexpect=4.8.0=pyh9f0ad1d_2
  - pickleshare=0.7.5=py_1003
  - pillow=9.2.0=py310hb3240ae_0
  - ply=3.11=py_1
  - prometheus_client=0.14.1=pyhd8ed1ab_0
  - prompt-toolkit=3.0.30=pyha770c72_0
  - prompt_toolkit=3.0.30=hd8ed1ab_0
  - psutil=5.9.1=py310h6c45266_0
  - pthread-stubs=0.4=hc929b4f_1001
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pygments=2.12.0=pyhd8ed1ab_0
  - pyparsing=3.0.9=pyhd8ed1ab_0
  - pyqt=5.15.7=py310h57cebac_0
  - pyrsistent=0.18.1=py310h1961e1f_1
  - python=3.10.5=hdaaf3db_0_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-fastjsonschema=2.15.3=pyhd8ed1ab_0
  - python-tzdata=2023.3=pyhd8ed1ab_0
  - python_abi=3.10=2_cp310
  - pytz=2023.3=pyhd8ed1ab_0
  - pyzmq=23.2.0=py310h85fb675_0
  - qt-main=5.15.4=h938c29d_2
  - qtconsole=5.3.1=pyhd8ed1ab_0
  - qtconsole-base=5.3.1=pyha770c72_0
  - qtpy=2.1.0=pyhd8ed1ab_0
  - readline=8.1.2=h3899abd_0
  - scipy=1.8.1=py310h1f9c157_0
  - seaborn=0.12.2=hd8ed1ab_0
  - seaborn-base=0.12.2=pyhd8ed1ab_0
  - send2trash=1.8.0=pyhd8ed1ab_0
  - setuptools=63.1.0=py310h2ec42d9_0
  - sip=6.6.2=py310hd4537e4_0
  - six=1.16.0=pyh6c4a22f_0
  - soupsieve=2.3.1=pyhd8ed1ab_0
  - sqlite=3.39.0=hd9f0692_0
  - stack_data=0.3.0=pyhd8ed1ab_0
  - statsmodels=0.14.0=py310hc1335a1_1
  - suitesparse=5.10.1=h7aff33d_1
  - tbb=2021.5.0=hbb4e6a2_1
  - terminado=0.15.0=py310h2ec42d9_0
  - tinycss2=1.1.1=pyhd8ed1ab_0
  - tk=8.6.12=h5dbffcc_0
  - toml=0.10.2=pyhd8ed1ab_0
  - tornado=6.2=py310h6c45266_0
  - traitlets=5.3.0=pyhd8ed1ab_0
  - typing_extensions=4.6.3=pyha770c72_0
  - tzdata=2022a=h191b570_0
  - unicodedata2=14.0.0=py310h1961e1f_1
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - webencodings=0.5.1=py_1
  - wheel=0.37.1=pyhd8ed1ab_0
  - widgetsnbextension=3.6.1=pyha770c72_0
  - xorg-libxau=1.0.9=h35c211d_0
  - xorg-libxdmcp=1.1.3=h35c211d_0
  - xz=5.2.5=haf1e3a3_1
  - zeromq=4.3.4=he49afe7_1
  - zipp=3.8.0=pyhd8ed1ab_0
  - zlib=1.2.12=hfe4f2af_2
  - zstd=1.5.2=ha9df2e0_2
  - pip:
    - matching==1.4
    - pip==22.1.2
    - pyqt5-sip==12.11.0
prefix: ~/opt/anaconda3/envs/PDBCleanV2
